version: '3.4'

services:
  identity.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS="http://+
      - ASPNETCORE_HTTP_PORTS=80
    ports:
      - "9000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
     # - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    depends_on:
      - db
    restart: on-failure
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
        - "1434:1433"
    environment: 
      - "SA_PASSWORD=3eiJz!?e8#s?3S!9"
      - "ACCEPT_EULA=Y"